on:
  push:
    branches:
    - master
    paths:
    - 'main.js'
    - 'action.yml'
    - '.github/workflows/test.yml'

  workflow_dispatch:

jobs:
  test:

    defaults:
      run:
        # -o verbose -o xtrace
        shell: bash --noprofile --norc  -o errexit -o pipefail -o nounset  -o verbose -o xtrace  -c 'source ~/fun.sh; source "$0" "$@"' {0}
  
    name: Test
    runs-on: ubuntu-latest
    steps:
    
    - name: "Let's go"
      uses: actions-rindeal/setup-bash-fun@master
    - run: test -f ~/fun.sh
    - run: ls -la ~/fun.sh
    - run: cat ~/fun.sh
    - run: |
        declare -p -f
    
